# Generated by Django 4.2.30 on 2026-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tractor_name', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horsepower', models.IntegerField()),
            ],
        ),
    ]
