# Generated by Django 4.2.30 on 2026-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tractor',
            name='stock_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20),
        ),
    ]
